### PR TITLE
Done the annonation based loading system

### PR DESCRIPTION
**Pull request by laci200270**
As the title says
A bit hacky but it works at least

### CODE REVIEW

**Comment by kde99** [comment]
```
warning: [options] bootstrap class path not set in conjunction with -source 1.6
L:\_______forge_latest\build\sources\main\java\useless\craft\blocks\UCBlocks.java:12: error: diamond operator is not supported in -source 1.6
    public static final HashMap<String, Block> blocks = new HashMap<>();
                                                                    ^
  (use -source 7 or higher to enable diamond operator)
L:\_______forge_latest\build\sources\main\java\useless\craft\items\UCItems.java:12: error: diamond operator is not supported in -source 1.6
    public static final HashMap<String, Item> items = new HashMap<>();
                                                                  ^
  (use -source 7 or higher to enable diamond operator)
L:\_______forge_latest\build\sources\main\java\useless\craft\tile\TileController.java:21: error: diamond operator is not supported in -source 1.6
        network = new HashMap<>();
                              ^
  (use -source 7 or higher to enable diamond operator)
L:\_______forge_latest\build\sources\main\java\useless\craft\unet\UNetworkMachine.java:41: error: default methods are not supported in -source 1.6
    default NetworkPreferredType getTypeOfMachine()
    ^
  (use -source 8 or higher to enable default methods)
4 errors
1 warning
```

azt mondtad h beállítod a java8-at

**Comment by kde99** [comment]
Feladom.... Lesz amilyen lesz...

**Comment by laci200270** [comment]
Be is állítottam

**Comment by kde99** [comment]
Mégsem ment...

**Pull request merged**
